---
title: "MAFMC Indicators Project Workshop 1 DRAFT Report"
author: "Sarah Gaichas, Gavin Fay, Kelsey Roberts, Sophie Wulfing, Connor Coscino, and Sarah Hope"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  word_document: default
csl: plos.csl
bibliography: operationalSOE.bib
link-citations: true
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Executive Summary

The Mid-Atlantic Fishery Management Council Inflation Reduction Act Project 5, "Operationalizing Ecosystem and Habitat Indicators to Support Climate-Ready Fisheries Management in the Mid-Atlantic" (MAFMC Indicators Project) held a hybrid workshop on December 10, 2025 in Baltimore, MD and online. The workshop objective was to identify and prioritize Council management decisions that could be supported or improved by operational use of ecosystem indicators. Workshop materials are posted at https://www.mafmc.org/council-events/2025/dec-10/indicators-workshop.

A total of 40 people attended the workshop. In-person attendees include 13 participants from the Council, Council Advisory Panels, Scientific and Statistical Committee (SSC), Council staff, and Atlantic States Marine Fisheries Commission staff, plus 4 from the project team. Online attendees included 21 participants from the Council, Council Advisory Panels, SSC, Council staff, Northeast Fisheries Science Center staff, Project Oversight Team, and other observers, plus 2 from the project team. 

The workshop included introductory presentations from the project team, followed by three discussions to address the question: Which management decisions should this project focus on, and why? Discussion 1 reviewed, clarified, and updated the [initial list of management decisions](https://www.mafmc.org/s/3_WK1_MgtDecisions.pdf). Discussion 2 identified 4 priority decisions for indicator development by the project team, detailed below. Discussion 3 provided initial feedback on [SMART indicator review](https://mafmc.github.io/SMARTindicatorsData/) documents and tools for refinement throughout the course of the project. The key takeaways of each discussion are outlined here, and detailed in the main report.

## Discussion 1: Clarify Decisions
*  Frame management decisions to reflect both restriction and liberalization 
*  Consider distinctions between: 
   +  Pre-season and inseason decisions 
   +  Short term and longer term planning horizons 
   +  Routine and emergency contexts 
*  Consider tradeoffs between objectives in decisions 
*  Consider uncertainty: indicators should reduce it 
*  Consider stages in the process where information is most useful 
*  Additions:  Quota management, Decisions regarding emerging fisheries, MMPA and ESA objective interactions with EFH, Strategic planning and Annual Action Plan, Cross-jurisdictional management 

## Discussion 2: Priority Decisions
*  **Risk policy:**  consider risk indicators in addition to stock status 
*  **Catch/quota setting:** communicate information available/used throughout the process. Consider Assessment, SSC ABC, Monitoring Committee, and Council processes 
*  **Measures setting:** consider multispecies and multifleet context and tradeoffs in the specifications process 
*  **Spatial management measures:** consider changing distributions of fish and fleets within the framework process  

#### For all selected decisions:
*  Evaluate performance of current management against stated objectives to aid indicator selection 
*  Evaluate impact of data availability or degradation on uncertainty and indicator performance 

## Discussion 3: Indicator Tools
*  The SMART Indicator framework and tools represent a promising approach for indicator evaluation
*  Add information on state level surveys and other information used in Habitat Assessment
*  Design indicator explorer tools to bring information into many different Council products and processes 

The next steps for the project are:

1. to develop a list of preliminary information sources that may contribute to indicators that address the priority management decisions, and 
1. to review this list during an online "mini-workshop" in late winter 2026 prior to full indicator development.


# Introduction

The Mid-Atlantic Fishery Management Council Inflation Reduction Act Project 5, "Operationalizing Ecosystem and Habitat Indicators to Support Climate-Ready Fisheries Management in the Mid-Atlantic" (MAFMC Indicators Project) has been designed to address the Council's April 2025 request to 

> "(1) conduct a comprehensive review of ecosystem and habitat indicators that will support management objectives, and (2) identify management processes, documents, and/or actions where ecosystem and habitat indicators can be integrated to inform management decisions."

The MAFMC Indicators Project addresses three Council objectives: 

1.  Review and assess existing ecosystem and habitat indicators in the Northeast and evaluate their utility to support management objectives. 
1.  Identify and develop priority ecosystem and habitat indicators, including associated targets and thresholds as appropriate, and identify specific pathways for incorporation into Council management processes, documents, or actions. 
1.  Create workflow and communication tools to support regular updates of indicators and that enhance usability of indicators in the management process. 

To address these objectives, the project team has been conducting a comprehensive review of existing indicators, has developed a framework for evaluating the indicators (described below), and organized an initial workshop to identify and prioritize Council management decisions that could be supported or improved by operational use of ecosystem indicators. This report summarizes the presentations, discussions, and outcomes of the workshop.

While the workshop was a [public meeting](https://www.federalregister.gov/documents/2025/11/18/2025-20056/mid-atlantic-fishery-management-council-mafmc-public-meeting) open to all interested participants, some Council, Advisory Panel, Scientific and Statistical Committee, and Council staff members were specifically invited to participate based on their prior experience with Council ecosystem and habitat indicators, and to encourage participation across a full range of stakeholder groups.

The in-person workshop was held on December 10, 2025 in Baltimore, MD, with an option for online attendance. Workshop materials are posted at https://www.mafmc.org/council-events/2025/dec-10/indicators-workshop. 

The workshop was well-attended. A total of 40 people attended the workshop. In-person attendees include 13 participants from the Council, Council Advisory Panels, Scientific and Statistical Committee (SSC), Council staff, and Atlantic States Marine Fisheries Commission staff, plus 4 from the project team. Online attendees included 21 participants from the Council, Council Advisory Panels, SSC, Council staff, Northeast Fisheries Science Center staff, Project Oversight Team, and other observers, plus 2 from the project team.

The workshop Agenda is included as Appendix 1 and the list of attendees is included as Appendix 2. The remaining workshop materials are included as Appendices 3-5. Presentations shown during the workshop are linked below. 

A 1-page Workshop Summary was also developed and is included as Appendix 6. 

# Workshop Presentation Summary

The workshop began with a round of introductions, followed by 3 introductory presentations. The [first presentation](https://sgaichas.github.io/HSpresentations/20250929_ProjectOverview_Gaichas.html) reviewed the overall MAFMC Indicators Project goals and objectives, timeline, current progress, and planned activities.  

The [second presentation](https://sgaichas.github.io/HSpresentations/20250929_Definitions_Gaichas.html) briefly defined terms to ensure clear communication. An *indicator* tells us something about where we are relative to our goals or to limits, or about the context we are working within that may affect achieving our goals. Examples of indicators currently reviewed by the Council include stock status indicators of fishing mortality relative to the mortality limit and stock biomass relative to target biomass. Other indicators can include measures of total commercial revenue or recreational effort that directly address broad management objectives, and contextual indicators of habitat conditions or other ocean uses that are not controlled by Council decisions but may indirectly affect Council decisions.

Indicator evaluation is using SMART criteria [@belcher_indicators_2024], where indicator attributes are defined as:

* **Specific**: clearly defined, describing exactly what is measured at what scale and how the indicator is calculated so that methods can be repeated. The indicator can be directly linked to a management process objective.

* **Measurable**: appropriate quantitative or qualitative data are available to evaluate change over time or in space. Tied to measurable management process objective. 

* **Achievable**: responses to changes in management are detectable within the management time frame--objectives tied to the indicator must be achievable. 

* **Relevant**: accurately reflects changes in the underlying process of concern. The indicator can be directly linked to a management process objective. 

* **Time-bound**: how often is indicator measured and does this align with the process of concern, and the management process?

SMART indicators should be Specific, Measurable, Achievable, Relevant, and Timely for the priority Council decisions. A SMART indicator for one process won't necessarily be SMART for another.

An **Operational** indicator is in use or ready for use. Components of an operational process include clear articulation of management objectives, standardized information updates on a regular reporting schedule, and feedbacks from the management system and adjustments to achieve management objectives. "Operationalizing" is an iterative process within a specific context.

The [third presentation](https://sgaichas.github.io/HSpresentations/20251104_Decisions_Gaichas.html) provided an overview of current uses of ecosystem indicators in the MAFMC management process, outlined general types of management decisions, and set the context for the workshop discussions and decisions to follow. Ecosystem indicators and information are currently used in the stock assessment process, in the SSC's determination of assessment uncertainty (overfishing limit coefficient of variation or "OFL CV" process), and in the MAFMC Ecosystem Approach to Fishery Management (EAFM) process. 

Stock assessments consider ecosystem information as a routine part of a research track assessment. Information approved for use in the research track assessment can then be used in management track assessments. Recent research track assessments in the Mid-Atlantic have included Ecosystem and Socioeconomic Profiles (ESPs) to address ecosystem factors important to the stock. Based on an ESP [@tabandera_black_2024], the Black Sea Bass management track assessment includes an ecosystem indicator (winter bottom temperature in the northern region) that reduces uncertainty in recruitment. When an ecosystem indicator is included in a stock assessment, the usual Council decisions proceed as they would for any assessment; no change to Council management decisions are required when using ecosystem information within an assessment. 

The [SSC's OFL CV process](https://www.mafmc.org/s/Final-OFL-CV-guidance-document_06_24.pdf) evaluates assessment uncertainty using a set of criteria for data quality, assessment model performance, ecosystem factors, comparisons with empirical estimates, and appropriate treatment of recruitment patterns.  The SSC routinely includes the results of the Northeast Climate Vulnerability Analysis [@hare_vulnerability_2016] as part of its evaluation of ecosystem factors that may affect assessment uncertainty. 

The [Council's EAFM process](https://www.mafmc.org/eafm) includes a structured decision framework [@gaichas_framework_2016] using ecosystem indicators from the annual Northeast Fisheries Science Center (NEFSC) [State of the Ecosystem report](https://www.fisheries.noaa.gov/new-england-mid-atlantic/ecosystems/state-ecosystem-reports-northeast-us-shelf) [@gaichas_state_2025] to inform an ecosystem-level risk assessment, where indicator trends or status translate to risk levels using Council-derived criteria [@gaichas_implementing_2018]. The Council has used its EAFM framework to develop a conceptual model of risks to the summer flounder fishery based on risk assessment results [@depiper_learning_2021]. The Council used the conceptual model to select a management issue for further analysis using management strategy evaluation (MSE) [@muffley_there_2021]. The summer flounder recreational discards MSE found several management strategies that could improve angler welfare with no change to stock status. In addition, the model developed for the MSE is now used operationally in annual recreational specification setting. 

The remainder of the presentation outlined categories of Council management decisions to help frame workshop discussions. Categories included Routine, Occasional, Tactical, and Strategic decisions. Routine and Occasional refer to timing of decisions. **Routine** decisions are made or reviewed annually or more often across all the managed stocks, while **Occasional** decisions are made as needed to address issues. Tactical and Strategic refer to scope of decisions. **Strategic** decisions consider long term, high level goals and objectives, while **Tactical** decisions implement the strategies in the short term. 

Finally, an example of a decision process that could be improved using SMART indicators was presented.

Workshop participants then referred to the list of management decisions compiled by the project and project oversight teams (Appendix 5) as the basis for Discussions 1 and 2.


# Workshop Discussion Summary

Discussions made up the majority of the workshop. In-person participants joined small group (~ 5 people) discussions where participants were assigned to one of three discussion subgroups for Discussions 1 and 2. Online participants joined a single online discussion subgroup. Each subgroup had a discussion facilitator from the project team and a note taker. After each small group discussion (~1 hour), participants reviewed the results from all groups in a plenary session. Notes from all discussions were reviewed and combined into this summary. Discussion 3 was conducted in plenary with all participants. 

## Discussion 1: Management Decision List Review

Workshop participants highlighted additional categories of management decisions and general considerations for incorporating indicators as well as reviewing the initial list of management decisions. 

Participants were concerned that some management decisions on the original list were phrased only in terms of restrictions. Because ecosystem information could highlight both positive and negative conditions, facilitators clarified that decisions could go in either direction from a baseline. Language describing management decisions was reframed to reflect both liberalization and restriction (see the Revised List of Management Decisions under Next Steps below).    

In addition to routine, occasional, tactical, and strategic categories of decisions, workshop participants highlighted important distinctions of timing, context, and planning. For example, pre-season and inseason decisions could both be routine, but require different types of information at different scales for optimal decision making. Therefore, the project team was encouraged to distinguish pre-season and inseason management decisions where appropriate.

Participants also highlighted different planning horizons among Council constituents that would require consideration when developing indicators for decision processes. For example, management agencies often have longer planning horizons than commercial or recreational fishers. This may necessitate indicators at multiple temporal scales for a decision process. 

Another contrast brought up during the workshop was between routine and emergency decisions. While emergency decisions likely fall within occasional timing, the urgency, timeframe, and available information for decision making differs from the other examples of occasional management decisions. Participants suggested that looking at past emergency actions might suggest indicators that could be used for several purposes, including determining what requires emergency action, or to establish triggers for Council action.

Considering a range of management objectives and identifying potential conflicts or tradeoffs between objectives was also a recommendation for the project. Potential management decisions were mapped to a range of management objectives based on the NMFS National Standards in the introductory presentation. Participants commented that these were not always considered together in decision making, and that conflicts over decisions may often arise due to competing objectives, or a different emphasis among objectives across user groups. 

Uncertainty was raised repeatedly as a challenge for management decision making. Many sources of uncertainty arise throughout the management process, from data collection through analyses and assessments to monitoring outcomes of decisions. Ideally, indicators would help explain sources of uncertainty, ultimately reducing uncertainty in the decision process. Indicators adding uncertainty to the decision process would be counterproductive. Therefore, it will be important for the project to account for changes in uncertainty due to the inclusion of indicators in priority decisions. 

Finally, an overarching consideration for the operational use of indicators is identifying where in the decision process indicator information is most useful. For example, some indicators may be best evaluated prior to conducting stock assessments and included in an assessment after review by the scientific working group. Other indicators may be needed for inseason decisions by the Council, so would need to be available well before a Council meeting and included in briefing materials to be considered. Presentation at the meeting would be too late for an informed decision. The timeline for priority management decisions will need to be specified with information needs at each step for effective decision making.

Workshop participants made several specific additions to the management decision list. In addition to changing language to reflect bi-directional decision making, the following items were added in each category:  

### Routine/Tactical: Specifications  
*  Commercial, state-level quota management

### Occasional, Tactical or Strategic: Framework Adjustment  
*  Exempted Fishing Permits (though GARFO decides, Council comments)
*  Seasonal or regional allocation
*  Emergency regulations

### Occasional and Strategic: more complex Council process  
*  Management units and stock definitions
*  Emerging fisheries (forage species, mantis shrimp, etc.)
*  Strategic planning and Annual Action Plan
*  Data collection standards
*  Interactions and tradeoffs among fisheries, essential fish habitat, endangered species, and marine mammal objectives
*  Cross-jurisdictional management; shared governance issues related to changing species distributions
*  Council advice/consultation/comment processes
*  Mechanisms for action (Categorical exclusions, Supplemental Information Reports)
*  NEPA analyses

One item was removed from the Occasional, tactical or strategic: framework adjustment category: Vessel size and horsepower restrictions.

An updated list is included in the Revised List of Management Decisions section under Next Steps below). 

## Discussion 2: Identify Priority Management Decisions

Four priority management decisions were identified at the workshop, representing a mix across the spectrum of routine or occasional and tactical or strategic decisions. The four priorities were Council risk policy, catch/quota setting, measures setting, and spatial management measures. It was noted that catch/quota setting and measures setting are fundamental decisions for fishery management, so these decisions were prioritized for indicator development by the project. Risk policy is the overarching strategic decision that shapes the more tactical catch and measures decisions, so it was likewise prioritized. All discussion subgroups brought up spatial management issues, so this was prioritized as well. We detail key considerations for these priority decisions here, and include other decisions that were discussed but ultimately not prioritized for this project below. 

Workshop participants noted that for the selected priority management decisions, the project should evaluate performance of current management against stated objectives to aid in indicator selection, and also evaluate the impacts of data availability or degradation on uncertainty and indicator performance. Initial performance metrics for the project were also discussed in general terms of defining a good decision. Good decisions were defined as those that were responsive and timely, incorporating new information as it becomes available, providing more flexible opportunities for fishing, and that involved a clear description of tradeoffs involved in the decision. In particular, participants highlighted the need to identify tradeoffs between objectives for different species and fleets in each of the priority decisions.

Council risk policy is currently designed to reduce the risk of overfishing below the maximum permissible level depending on stock biomass status (B/Bmsy). This policy has been simulation tested for performance relative to the single risk indicator of B/Bmsy across multiple life history types representative of MAFMC stocks. While stock status is an important indicator, there may be other factors that affect the Council's ability to optimize yield from fisheries while maintaining fishing mortality within legal limits. For example, stock productivity may be maintained across a wider range of B/Bmsy than currently recognized when habitat conditions are favorable. Conversely, a rapid decline in habitat conditions may reduce productivity for a stock that is well above its Bmsy. Identifying relationships between selected indicators and stock biomass status will be important for the performance of the risk policy for the target stock, as well as potential implications between stocks. Evaluating both current performance of the risk policy, and tradeoffs across multiple objectives beyond individual stock biomass and mortality objectives were also emphasized in discussion.

For catch and quota setting, participants identified a clear need to first describe the entire process along with information available and used at each step. Analysis would consider assessment, SSC, Monitoring Committee, and Council decision processes. Because the SSC ABC decision constrains later decisions (ABC cannot be exceeded), it was noted that evaluating options for the use of indicators in the assessment process and by the SSC would be beneficial. In particular, indicators addressing, explaining, or ideally reducing key ABC uncertainties would be most useful. However, indicators might be useful beyond SSC decisions by facilitating Council decisions on specifications when multiple options for ABC are available (e.g. multi-year specifications based on an averaged constant ABC or individual year ABCs from the SSC). Further, indicators presented to the Council could provide context for SSC decisions and help clarify Council decisions. Finally, indicators of performance across multiple objectives for catch/quotas could be useful in Council consideration of tradeoffs. Other Councils are developing processes to use indicators in their catch and quota setting processes, which can also be reviewed by the project. 

While catch/quota setting decisions specify how much to fish, measures setting decisions specify how to fish in terms of timing, areas, sizes, etc. Participants noted the challenges associated with setting measures for individual stocks when these decisions can have side effects on other stocks available to multispecies, multifleet fisheries. Constraining measures for one species when only a few others are available may result in an unintentional increase in fishing pressure on the other species. Ideally, information would be available across stocks within a region so that measures to reduce fishing risk for individual species might be considered alongside an objective to maintain as broad a set of fishing opportunities as possible. Indicators of the number and diversity of fishing opportunities available to a particular fleet sector in a given time and area may help evaluate these tradeoffs. 

Spatial management was recognized as a subset of measures setting, but one that participants noted had good potential to use ecosystem information on distributions and habitat conditions that could be derived from multiple data sources. Evaluating the effectiveness of current spatial measures and robust indicator testing before use was emphasized in all discussion groups. Many participants identified needs for both near-real time observational indicators and projections of conditions such as temperature, or of seasonal habitats such as the cold pool for different spatial management decisions. Some spatial indicators could achieve management objectives for e.g. bycatch reduction if appropriate indicator information were made available to fishery participants so that they could decide how to avoid bycatch, rather than the Council setting measures (similar to the [Turtlewatch](https://oceanwatch.pifsc.noaa.gov/turtlewatch.html) approach in the Pacific as opposed to time-area bycatch closures [@vanwert_hawaiis_2025]). For other decisions such as habitat conservation areas, Council decisions could consider changing distributions of fish and fleets within the framework process.

Additional management decisions that were discussed but ultimately not moved forward as priorities for analysis included the annual priority setting process and permitting decisions. The annual priority setting process is high level and strategic, and could possibly be informed by contextual indicators. However, it was suggested that a brand new suite of indicators may not be necessary for this process, and that operationalizing the contextual use of indicators in a process this broad may provide fewer benefits for the Council than some of the other proposed priority decisions.

Permitting decisions were discussed by the full group. While there could be benefits to considering indicators in the permitting decision process, in particular to evaluate tradeoffs resulting from permitting decisions, there was reluctance to embark on analysis of indicators for permitting decisions in this project without a fuller review of current permitting practices across the Council region and in adjacent jurisdictions. This was considered a longer term and separate task.  

## Discussion 3: Progress on Indicator Review

A brief overview of progress to date on the comprehensive indicator review (the project's first objective) was presented to close the workshop. This overview included demonstrations of an online SMART Indicator Report and a prototype online interactive SMART Indicators Summary Tool, as well as a summary of investigations into indicator frameworks used by other organizations. 

The online [SMART Indicator Report](https://mafmc.github.io/SMARTindicatorsData/) includes information on the attributes of each existing indicator to facilitate evaluation against SMART criteria. The format of the report was developed in consultation with the project oversight team from the beginning of the project to ensure that indicator information was captured in one place to both describe indicators and their potential for operational use. The report is built using reproducible methods and publically available code at https://github.com/MAFMC/SMARTindicatorsData so that it can be updated by Council staff after this project is complete. For existing indicators, the report can pull in available data, documentation, and descriptions. For example, NEFSC State of the Ecosystem indicators are described using information drawn from the publically available ecodata dataset, online indicator catalog, and online technical documentation. There are also methods to enter information for indicators that are documented differently so that they can be evaluated in the same format. The report includes a preliminary framework to evaluate each indicator against SMART criteria, based on the information found in online indicator documentation. This evaluation is not yet specific to management decisions, so it looks at more generic indicator attributes such as the existence and availability of source data, documentation of methods, inclusion of clear units, etc. There are currently over 60 indicators included in this report.

Using the preliminary evaluations in the SMART Indicator Report, a prototype [SMART Indicator Summary Tool](https://sgaichas.shinyapps.io/SMARTindicatorsDashboard/) has been developed to explore and filter the indicators that might be most useful for a particular management application. At present, preliminary SMART criteria scores for  indicators in each category can be summarized in the tool. There are plans to include the ability to filter by area, minimum time series length, SMART score, or management decision type. This is a very new tool, still under construction, and the project team welcomed any feedback on how to structure the interface to make it most useful for Council purposes. 

A final brief presentation looked beyond the Northeast US region to explore indicator frameworks used in other contexts. The United Nations Fisheries and Agriculture Organizations (UN FAO) indicator framework to evaluate progress against Sustainable Development Goals (SDG) was presented as an operational indicator framework. It was not suggested that MAFMC could directly use indicators in this framework, but rather that there may be aspects of the framework or its use that could assist the Council in developing its own approaches. The indicators presented meet SMART criteria, and focused on socioeconomic information and how it is used to track progress against the SDG on global food security as a demonstration of how the framework is used.

Workshop participants had many constructive comments and suggestions for further development of the indicator review and tools by the project team. Overall, they found that the SMART Indicator framework and tools represented a promising approach for indicator evaluation. There were several suggestions for additions of indicator data, in particular the state surveys and other information integrated into the Northeast Regional Habitat Assessment. Overall there was a desire to design the tools with enough flexibility to be used in multiple different Council products and processes, by Council Staff and others involved in analysis and decisions. In addition, the importance of including socioeconomic indicators and data in Council decision processes was emphasized.

# Next Steps

## Revised List of Management Decisions

The list of management decisions has been revised here to emphasize that both restriction and liberalization of management are possible based on ecosystem conditions. Some decisions were added to the list and one was removed based on group discussions. 

### Routine/Tactical: Specifications

*  Catch limits and targets (OFL, ABC, OY, ACL, ACT)
*  Landings limits (commercial quotas, recreational harvest limits, total allowable landings limits, etc.)
*  Minimum fish sizes (commercial and/or recreational - maximum sizes can also be specified for a few species/sectors)
*  Trip/possession limits (commercial and/or recreational)
*  Gear requirements (e.g., commercial minimum mesh sizes, pot/trap escape vent size requirements)
*  Open/closed seasons (recreational; commercial fisheries can close in-season if the quota is met before the end of the season)
*  Reporting requirements specific to each FMP
*  Commercial bycatch or recreational discard caps (apply to only a subset of MAFMC species)
*  Commercial, state-level quota management

### Routine/Tactical: SSC

*  Best scientific information determination (includes scientific working group and review panel judgement)

### Occasional, Tactical or Strategic: Framework Adjustment

*  ABC control rules
*  Risk policy
*  Accountability measures
*  Permitting requirements (could require amendment)
*  Exempted Fishing Permits (though GARFO decides, Council comments)
*  Essential Fish Habitat (EFH) and HAPCs 
*  Vessel Monitoring System (VMS) requirements
*  Spatial management areas (e.g., closed areas, gear requirement areas, exemption areas) 
*  Commercial quota allocations 
*  Commercial/recreational allocations (for some FMPs)
*  Seasonal or regional allocation
*  Onboard observer requirement (for some FMPs)
*  Changes to Standardized Bycatch Reporting Method 
*  Deep Sea Coral Protection Zone boundaries and regulations
*  Emergency regulations

### Occasional and Strategic: more complex Council process

*  FMP development and amendment 
*  Management units and stock definitions
*  Emerging fisheries (forage species, mantis shrimp, etc.)
*  Research priority development and review
*  Strategic planning and Annual Action Plan
*  Data collection standards
*  Ecosystem Approach to Fisheries Management (EAFM) guidance
*  “Measures contained within this [Framework] list that require significant departures from previously contemplated measures or that are otherwise introducing new concepts may require amendment of the FMP instead of a framework adjustment.” 
*  Policy development on other ocean activities
*  Interactions and tradeoffs among fisheries, essential fish habitat, endangered species, and marine mammal objectives
*  Cross-jurisdictional management; shared governance issues related to changing species distributions
*  Council advice/consultation/comment processes
*  Mechanisms for action (Categorical exclusions, Supplemental Information Reports)
*  NEPA analyses


## Identifying Potential Information Sources for Priority Decisions

The project team will next identify existing indicators and/or promising data sources to inform the priority management decisions. The team will also identify available tools for evaluating both performance of current management, and performance of management with new proposed indicators for each of the decisions. 

For example, evaluating current performance of the risk policy would involve a similar analysis as was done to develop the risk policy, with population models based on MAFMC stock assessments and many simulated iterations of risk-policy based catch limits over time for multiple stocks at multiple levels of data quality and process uncertainty. Additional information from ESPs on key ecosystem influences for stocks could be included in the population models both to test impacts on current risk policy performance, and to evaluate whether including ecosystem information explicitly in the risk policy improves performance relative to management objectives. This type of analysis could rely on existing indicators from ESPs or the SOE, or might require new indicator development.

In contrast, evaluating performance of spatial measures setting involves a more spatially explicit model and spatially explicit ecosystem and fishery information, as well as information on spatial distribution over time for both fish and fisheries. Spatially explicit data and modeling frameworks are available for the Mid-Atlantic region. The project team will assemble a list of information sources relevant to each priority decision over the coming months.

An online "mini-workshop" will review the gathered information in late winter/early spring 2026 to review the information and outline further work. 

## Continue Development of Indicator Tools

Workshop participants had several constructive suggestions for continued development of the indicator tools that the team will address over the coming months. Improvements will strive to provide indicator information for as many different Council products and processes as possible. 

Planned adjustments and improvements to the SMART Indicator Review web catalog:  

*  Add information on state level survey indicators and other survey information currently included in the Habitat Assessment 
*  Continue to bring in other data sources from MARCO, EPA, and individual states 

Planned adjustments and improvements to the SMART Indicator Summary Tool:  

*  Include brief indicator descriptions and link back to the fuller set of indicator information found in the SMART Indicator Review page for each indicator 
*  Include additional indicators as they are added to the SMART Indicator Review 
*  Allow for filtering to time scales appropriate to in-season decisions (months, weeks or days instead of years) 
*  Include methods to evaluate demand for specific indicators linked to specific processes 

Work on the SMART Indicator tools will continue on the MAFMC's public GitHub organization (https://github.com/MAFMC) in consultation with the project oversight team and any other interested parties. 



# List of Appendices

1. Workshop [Agenda](https://www.mafmc.org/s/Workshop-1-Final-Agenda.pdf)
1. Workshop Attendees
1. Workshop Overview [1-pager](https://www.mafmc.org/s/1_WK1_Overview.pdf)
1. Definitions [1-pager](https://www.mafmc.org/s/2_WK1_Definitions.pdf)
1. Management Decisions [1-pager](https://www.mafmc.org/s/3_WK1_MgtDecisions.pdf)
1. Workshop Results 1-pager

# References


