---
title: |
output:
  pdf_document:
    keep_tex: true
    includes:
      in_header: latex/boxescolumns.tex
  html_document:
    css: columns.css
    df_print: paged
geometry: margin = 0.5in
link-citations: true
urlcolor: blue
---

\vspace{-1cm}
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE)

library(patchwork)

# can I set up 2 columns with highlight boxes in each? yes

```

# Catch/Quota Setting: Potential Indicators and Pathways (Overview)

::: {.noteblock data-latex=""}
Catch and Quota Setting is a multistep process involving decisions by the Northeast Regional Coordinating Committee (NRCC; including the Mid Atlantic and New England Councils, Atlantic States Marine Fisheries Commission, and NOAA's Greater Atlantic Regional Fisheries Office and Northeast Fisheries Science Center), assessment scientists, assessment peer reviewers, the Council's Scientific and Statistical Committee (SSC), and the Council. Information for each stock and fishery is reviewed and synthesized to determine catch and quota levels that meet management objectives.
:::

*  **Key question: What additional indicators could inform decisions at different steps in the Catch/Quota setting process? Could habitat, ecosystem, or socioeconomic indicators improve the process?** 
*  **Scope: Should we develop a general process for using indicators in the catch/quota setting process, or focus on a specific application for a single species? Which species?** 


:::::: {.cols data-latex=""}

::: {.col data-latex="{0.49\textwidth}"}
::: {.ltbluebox data-latex=""}
## What information is used now?

::: {.ltpurplebox data-latex=""}
1. Determine Assessment Priorities

The NRCC prioritizes stocks for assessment based on management needs,
fishery importance, stock status and trend, ecosystem importance, assessment information, and stock
biology. Terms of Reference (ToRs) ensure the assessment process delivers consistent, management-relevant outputs.
::: 

::: {.ltpurplebox data-latex=""}
2. Conduct Assessment

Assessment scientists assemble and analyze fishery dependent and independent data and develop models to synthesize the data and produce outputs meeting the assessment ToRs. 
::: 

::: {.ltpurplebox data-latex=""}
3. Review Assessment

Independent reviewers evaluate whether assessments ToRs are met, data is appropriate, and methods reflect best practices.
::: 

::: {.ltpurplebox data-latex=""}
4. Determine Acceptable Biological Catch

The SSC uses reviewed assessment outputs within a structured framework to determine ABC from assessment uncertainty based on input data, model diagnostics and performance, and ecosystem considerations.
::: 

::: {.ltpurplebox data-latex=""}
5. Catch Specification

The Council decides whether annually varying or averaged ABCs will be used in multiyear harvest specifications, then allocates the ABC to harvest sectors. Management uncertainty is determined and applied, then discards are estimated and subtracted to derive quotas and harvest limits.
::: 




:::

:::

::: {.col data-latex="{0.02\textwidth}"}
\ 
<!-- an empty Div (with a white space), serving as
a column separator -->
:::

::: {.col data-latex="{0.49\textwidth}"}
::: {.ltgreenbox data-latex=""}
## Information sources for indicators 

[Ecosystem and Socioeconomic Profiles](https://www.fisheries.noaa.gov/new-england-mid-atlantic/ecosystems/ecosystem-and-socioeconomic-profile-development-and-reports) conceptual models and indicators for MAFMC stocks:

*  Black Sea Bass 
*  Golden Tilefish
*  Longfin squid 
*  Shortfin squid

[State of the Ecosystem](https://www.fisheries.noaa.gov/new-england-mid-atlantic/ecosystems/state-ecosystem-reports-northeast-us-shelf) and [Risk Assessment](https://www.mafmc.org/s/2_MAB_RiskAssess_2024.pdf) indicators

The fish and invertebrate [Climate Vulnerability Analysis](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0146756) sensitivity, exposure and vulnerability rankings

And many other potential sources (survey data, GLORYS ocean reanalysis)

### Potential Pathways

Ecosystem information can enter at some portion of steps 1, 2, 4, and 5. 


::: {.ltpurplebox data-latex=""}
## Information gaps 

What is missing and/or would be a lot of work

::: 
:::
:::

::::::




