---
title: |
output:
  pdf_document:
    keep_tex: true
    includes:
      in_header: latex/boxescolumns.tex
  html_document:
    css: columns.css
    df_print: paged
geometry: margin = 0.5in
link-citations: true
urlcolor: blue
editor_options: 
  markdown: 
    wrap: 72
---

\vspace{-1cm}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE)

library(patchwork)

# can I set up 2 columns with highlight boxes in each? yes

```

# Measures Setting: Potential Indicators and Pathways

::: {.noteblock data-latex=""}
Measure setting is the process of establishing regulatory controls and conservation tools that govern how, when, where, and how much fish can be harvested to prevent overfishing and ensure the long-term sustainability of stocks. **Here we emphasize measures governing how, when, and where to harvest, because how much to harvest is described separately under Catch/Quota setting.** Measures could include regulations such as gear requirements, spatial or temporal openings and closures, and size and bag limits. 
:::

-   **Key question: What indicators could inform measures
    setting across all stocks? Could ecosystem indicators or recreational demand
    indicators in addition to current information improve the process?**
-   **Scope: Should we develop a general process evaluating multifleet objectives in
    the measures setting process?**

::: {.cols data-latex=""}
::: {.col data-latex="{0.49\\textwidth}"}
::: {.ltbluebox data-latex=""}
## What information is used now?

Current measures are outlined by NOAA's [Specification Summaries](https://www.fisheries.noaa.gov/species-directory) and their [Federal Regulations](https://www.fisheries.noaa.gov/rules-and-regulations/fisheries).

\vspace{2ex}

Measures are set for individual stocks within FMPs to "establish allowable harvest levels that will prevent overfishing, consistent with the most recent scientific information."  

*   Commercial measures include gear requirements, seasons, and areas. The goals of measures are listed in FMPs, for example Summer Flounder FMP Objective 3.1 is to "Provide reasonable access to the fishery throughout the management unit. Fishery allocations and other management measures should balance responsiveness to changing social, economic, and ecological conditions with historic and current importance to various user groups and communities." 
*   Recreational measures include recreational bag, size, and season limits. Recreational measures are designed to achieve the target level of harvest, informed by the Recreational Harvest Limit (RHL) and stock status. Measures can also be informed by other considerations such as angler welfare. 
*   Measures are set in specifications. The process for setting measures can be changed by either FMP amendment or framework action. 

\vspace{2ex}

Workshop 1 discussions centered on maximizing fishing opportunities across species and fleets when setting measures for individual species. **Opportunities across species are not typically considered when setting measures for individual species.**

::: {.ltpurplebox data-latex=""}
This emphasizes the multifleet/multispecies aspect highlighted in the workshop to ensure overall opportunities are maximized, but ecosystem indicators could also be used in single species measures without considering this (e.g. projected conditions impact on growth could lead to different fish size or gear recommendations, changing seasonality of migration or spawning could lead to different open/closed seasons, etc) simpler but less focused on a system level objective. 
:::

:::
:::

::: {.col data-latex="{0.02\\textwidth}"}
  <!-- an empty Div (with a white space), serving as
a column separator -->
:::

::: {.col data-latex="{0.49\\textwidth}"}
::: {.ltgreenbox data-latex=""}
## Information sources for indicators

To understand multispecies, multifleet implications of measures set for
a given species, we need:

-   What fleets the species is caught in.

    -   [CAMS](https://www.fisheries.noaa.gov/new-england-mid-atlantic/commercial-fishing/quota-monitoring-greater-atlantic-region)
        data for commercial fleets
    -   [MRIP](https://www.fisheries.noaa.gov/recreational-fishing-data/introduction-marine-recreational-information-program-data)
        for recreational fleets

-   Other targets and catch from these fleets

-   Who manages the other species and fleets if not MAFMC

-   Measures in place for all the other species (commercial and
    recreational) caught with the species of interest

\vspace{2ex}

Big picture performance metrics for commercial and recreational
fisheries (landings, revenues, trips, and other system level fishery attributes) are available in:

-   [State of the Ecosystem
    Reports](https://www.fisheries.noaa.gov/new-england-mid-atlantic/ecosystems/state-ecosystem-reports-northeast-us-shelf)
-   [EAFM Risk
    Assessments](https://static1.squarespace.com/static/511cdc7fe4b00307a2628ac6/t/672bbef75e7b1166ec15dba9/1730920200863/2_MAB_RiskAssess_2024.pdf)
-   [Ecosystem and Socioeconomic
    Profiles](https://www.fisheries.noaa.gov/new-england-mid-atlantic/ecosystems/ecosystem-and-socioeconomic-profile-development-and-reports)

-   Stock assessment projections of age and size compositions
-   Rec Demand Model projections of commercial fleet and angler response to measures (summer flounder, scup, and black sea bass only)
    - Threshold for switching target species?

-   Projections of climate and habitat conditions for relevant species
    -   [Changing Ecosystems and Fisheries Initiative](https://psl.noaa.gov/cefi_portal/)

-   Projections of species overlap; see [river herring](https://www.rhapcast.org/) bycatch mitigation IRA project

### Potential Pathways

Develop a live view of all current measures by species and fleet that shows effects of changes for one stock. 

::: {.ltpurplebox data-latex=""}
## Information gaps

Aggregate performance metrics for the fisheries to evaluate implications of changes (commercial and recreational): 

-   Expenditures 
-   Resilience 

Easily accessible, up to date measures in place for all species across all states


:::

:::
:::


:::
