---
title: |
output:
  pdf_document:
    keep_tex: true
    includes:
      in_header: latex/boxescolumns.tex
  html_document:
    css: columns.css
    df_print: paged
geometry: margin = 0.5in
link-citations: true
urlcolor: blue
---

\vspace{-1cm}
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE)

library(patchwork)

# can I set up 2 columns with highlight boxes in each? yes

```

# Risk Policy: Potential Indicators and Pathways

::: {.noteblock data-latex=""}
Risk policy is a Council-level decision. Current [risk policy](http://www.mafmc.org/s/MAFMC-ABC-Control-Rule-White-Paper.pdf) uses stock status as the only indicator of when to adjust risk tolerance. Low stock status results in much more risk averse probability of overfishing and lower ABC relative to OFL, high stock status (>1.5 B/Bmsy) is as risk tolerant as allowed by law with ABC close to OFL. 
:::

**Key question: What additional indicators could inform Council risk tolerance? Could habitat conditions or socioeconomic indicators in addition to stock status tell us whether we can be more or less risky?** 

## Scope 

::: {.ltgreenbox data-latex=""}
Questions for consideration to adjust the scope
(e.g. demo for one species or develop a more general approach/process for all?)
:::


:::::: {.cols data-latex=""}

::: {.col data-latex="{0.49\textwidth}"}
## What information is used now for the decision?

Sources by scope?

Outline the process

Outline specific info for species level decision

:::

::: {.col data-latex="{0.02\textwidth}"}
\ 
<!-- an empty Div (with a white space), serving as
a column separator -->
:::

::: {.col data-latex="{0.49\textwidth}"}

## Information sources to develop indicators

List current info sources from google doc

:::

::::::

::: {.ltpurplebox data-latex=""}
## Information gaps 

What is missing or would be a lot of work

::: 





