---
title: |
output:
  pdf_document:
    keep_tex: true
    includes:
      in_header: latex/boxescolumns.tex
  html_document:
    css: columns.css
    df_print: paged
geometry: margin = 0.5in
link-citations: true
urlcolor: blue
---

\vspace{-1cm}
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# can I set up 2 columns with highlight boxes in each? yes

```

# Management Decisions

Drawn from Mid-Atlantic FMPs. Decisions are made through specifications, frameworks, SSC, amendment and other processes.

## Definitions:

::: {.noteblock data-latex=""}
Routine and Occasional refer to timing of decisions. **Routine** decisions are made or reviewed annually or more often across all the managed stocks, while **Occasional** decisions are made as needed to address issues. 
:::

::: {.noteblock data-latex=""}
Tactical and Strategic refer to scope of decisions. **Strategic** decisions consider long term, high level goals and objectives, while **Tactical** decisions implement the strategies in the short term. 
:::


:::::: {.cols data-latex=""}

::: {.col data-latex="{0.49\textwidth}"}
::: {.ltgreenbox data-latex=""}
## Routine/Tactical: Specifications

*  Catch limits and targets (OFL, ABC, OY, ACL, ACT)  
*  Landings limits (commercial quotas, recreational harvest limits, total allowable landings limits, etc.)  
*  Minimum fish sizes (commercial and/or recreational - maximum sizes can also be specified for a few species/sectors)  
*  Trip/possession limits (commercial and/or recreational)  
*  Gear restrictions (e.g., commercial minimum mesh sizes, pot/trap escape vent size requirements)  
*  Open/closed seasons (recreational; commercial fisheries can close in-season if the quota is met before the end of the season)  
*  Reporting requirements specific to each FMP  
*  Commercial bycatch or discard caps (apply to only a subset of MAFMC species)  

## Routine/Tactical: SSC

*  Best scientific information determination (includes scientific working group and review panel judgement)
:::
:::

::: {.col data-latex="{0.02\textwidth}"}
\ 
<!-- an empty Div (with a white space), serving as
a column separator -->
:::

::: {.col data-latex="{0.49\textwidth}"}

::: {.ltbluebox data-latex=""}
## Occasional, Tactical or Strategic: Framework Adjustment

*  ABC control rules  
*  Risk policy  
*  Accountability measures  
*  Permitting restrictions (could require amendment)   
*  Essential Fish Habitat (EFH) and HAPCs  
*  Vessel Monitoring System (VMS) requirements  
*  Spatial management areas (e.g., closed areas, gear restricted areas, exemption areas)  
*  Commercial quota allocations  
*  Commercial/recreational allocations (for some FMPs)  
*  Vessel size and horsepower restrictions  
*  Onboard observer requirement (for some FMPs)  
*  Changes to Standardized Bycatch Reporting Method  
*  Deep Sea Coral Protection Zone boundaries and regulations
:::

:::
::::::

::: {.ltpurplebox data-latex=""}
## Occasional and Strategic: more complex Council process

*  FMP development and amendment  
*  Stock definition  
*  “Measures contained within this [Framework] list that require significant departures from previously contemplated measures or that are otherwise introducing new concepts may require amendment of the FMP instead of a framework adjustment.”  
*  Consulting/commenting on other ocean activities  
:::



